language: python
matrix:
  include:
  - os: linux
    python: '3.6'
  - os: osx
    language: generic
    env: PYTHON=3.6.5
addons:
  apt:
    packages: libudev-dev libusb-1.0-0-dev libfox-1.6-dev
# Install Python for macOS. Taken from https://pythonhosted.org/CodeChat/.travis.yml.html.
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    # Per the `pyenv homebrew recommendations <https://github.com/yyuu/pyenv/wiki#suggested-build-environment>`_.
    brew install xz zlib
    # See https://docs.travis-ci.com/user/osx-ci-environment/#A-note-on-upgrading-packages.
    brew outdated pyenv || brew upgrade pyenv
    brew outdated sqlite3 || brew upgrade sqlite3
    brew outdated readline || brew upgrade readline
    brew outdated openssl || brew upgrade openssl
    # virtualenv doesn't work without pyenv knowledge. venv in Python 3.3
    # doesn't provide Pip by default. So, use `pyenv-virtualenv <https://github.com/yyuu/pyenv-virtualenv/blob/master/README.md>`_.
    brew install pyenv-virtualenv
    export PYTHON_CONFIGURE_OPTS="--enable-shared --disable-static"
    pyenv install $PYTHON
    # I would expect something like ``pyenv init; pyenv local $PYTHON`` or
    # ``pyenv shell $PYTHON`` would work, but ``pyenv init`` doesn't seem to
    # modify the Bash environment. ??? So, I hand-set the variables instead.
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    # A manual check that the correct version of Python is running.
    python --version
    pip install -U pip
    pip install -U pyinstaller
  fi
install: pip install -r requirements.txt
script: pyinstaller znode-tool.spec
deploy:
  provider: releases
  api_key:
    secure: XuAVHmFWAB0IionyqvrRSpGFJlezJKHrwxXqqcpT+49sEzdhk9gOyV87QPP8/jADPMZbrzotONr2it9lqLosA34lohTtWPtUCgROSbRZYUbMUxWlI+K26k3P3U1wCbV22sx/PzC1C0EYQ6IcA4nxkDPxi9rd5nrbdXRCxvAAUFteMhYo28dnXfZ4WJFJmuVesF2hBZYbi0xx1x7vCSyDx3HHWSrDBS2rugMuxLZDivgcBjyhv1dbuArGnjbrUzlp3iu0nVx53+rBfG5x+3sdM4CZti2quAvv9WMCoe73OEViwqdWzXxgEgMkfj8R6FTdFVG491FLX1oCQdhSreVAucp+Crmhfuct+gewrGXs0XrVNog7fGWIMfwR+3YL3JZdPD5nf+tJIsOIn2VAkGzCU9VtqfavYmlgsIun6IB5CT3vu/4DtUiOO8dxwUHVFuQ5JDRmnskoHXm3FqRuzl7tzure5HF0i5e1RSVmv67YDcvEAygdlCEpxxzgxVy+cLU0CAD7jqlvxeh7XtDa8JiWMbq00aNSQ+wNQ/8FuB9FeEKpgF4a6ia8Hd3U2YJQVxP1PG1gIF8Iu1WXSI07hjuhZ8YDy1qDd8VksmDt0kv1jn+1klPX+4fBkcaRuLiV1HoungLUZkSWTEp3LlQtrbaahIExLYXDyzO91ufeFJXeO3E=
  skip_cleanup: true
  file_glob: true
  file: all/ZnodeTool_*
  on:
    tags: true
    # repo: yura-pakhuchiy/znode-tool
